### PR TITLE
feat: Add `tree-sitter-rust`.

### PR DESCRIPTION
**Pull request by duesee**
This PR adds Rust support. This is related to https://github.com/GumTreeDiff/gumtree/pull/296.

### CODE REVIEW

**Comment by jrfaller** [comment]
Hi and thanks a lot for the PR! I have been meaning to add rust for some time so let's do it.

However I am not sure how to use the test files you provide? Should we add some unit tests for the parsers?

**Comment by duesee** [comment]
> However I am not sure how to use the test files you provide? Should we add some unit tests for the parsers?

Sorry, I added these files last minute :-) They are meant as a basis for a simple "sanity test". Without the "flattened" config, `tree-sitter-parser` produces identical XML outputs for two files that are meaningfully different. I can add a unit test that makes sure the XML output is different. Do you have a preference how to do that, e.g., what unit testing framework to use (unittest, pytest, ...)?

**Comment by duesee** [comment]
I tried to add some `pytest` tests but some changes are required to `tree-sitter-parser.py`. Thus, I removed the test files from this PR (for now) and will open another one that adds some Rust tests. Hope that's okay -- and happy to get this in :-)

**Comment by jrfaller** [comment]
Yes good idea! It's not trivial to have tests in this project. Ideally we could have the code snippets directly in the test files. I guess the goal of the tests would be to assert we have the expected tree shapes when applying the rewrite rules, but it's kind of a tough (and boring) oracle to write. Not sure how to do better though...

**Pull request merged**
