### PR TITLE
Add support for CMake

### PR DESCRIPTION
**Pull request by mahtab-nejati**
This commit adds support for CMake.

### CODE REVIEW

**Comment by jrfaller** [comment]
Hi!

There was a bug but now it's fixed.

However there are no tests at all, do you have some sample of CMake code I could add into a test case?

**Comment by mahtab-nejati** [comment]
Thanks for resolving the bug. Here is the content of a sample `CMakeLists.txt` file for testing purposes:

```
option(BUILD_SERVER "des1" YES)
option(FEATURE_IRC_SERVER "des2" YES)

option(foo "Is bar?" YES)
option(john "Is john?" YES)

set(SERVER_SRC files_for_test/a.cxx)
if(APPLE)
    set(APP_VERSION 2)
else()
    set(APP_VERSION 1)
endif()

if(BUILD_SERVER)
    if(FEATURE_IRC_SERVER)
        list(APPEND SERVER_SRC files_for_test/b.cxx)
    else()
        list(APPEND SERVER_SRC files_for_test/c.cxx)
    endif(FEATURE_IRC_SERVER)
endif(BUILD_SERVER)

if(APP_VERSION GREATER 1 OR LINUX)
    list(APPEND SERVER_SRC unix/new.cxx)
endif()

add_executable(exec ${SERVER_SRC})
add_library(lib another_folder_for_test/*.cxx)
if(foo)
    if(john)
        target_link_libraries(exec lib)
    endif()
endif()
```

**Comment by jrfaller** [comment]
OK thanks for the code. I guess it is working as expected, but you can take a look :

- https://github.com/GumTreeDiff/tree-sitter-parser/blob/main/tests/test_cmake.py
- https://github.com/GumTreeDiff/tree-sitter-parser/blob/main/tests/snapshots/test_cmake/test_class_definition/cmake_build.txt

However I have the impression that the resulting AST could be cleaned from the `(` and `)` right?

**Comment by mahtab-nejati** [comment]
Thanks. The tree looks as expected. One could choose to clean the tree further depending on their use case. I would leave it until I test this with the GumTree and see if it affects the output much.

**Comment by jrfaller** [comment]
Yes! About that, do you plan to make also a PR to integrate a new tree generator in gumtree? Cheers!

**Comment by mahtab-nejati** [comment]
Yes, I'm working on integrating the tree-sitter parser and using the output tree in GumTree. I will make the PR as soon as I'm done with testing it.
Best

**Pull request merged**
