### PR TITLE
refactor: Refactor (and extract) a `tree_sitter_parser` module.

### LINKED ISSUE #7: tests: Agree on (and add) a test framework.
We probably want some tests here that assure that `tree-sitter-parser` does what we expect it to do.

Before writing tests, we need to agree on a test framework. `pytest` seems easy to use and less verbose than Python's `unittest`.

### PR DESCRIPTION
**Pull request by duesee**
This PR extracts a module (`tree-sitter-parser/__init__.py`) from `tree-sitter-parser.py` so that it can be used in tests.

I marked this PR as a draft for now because it may be difficult to review. If you are interested in these changes I can try to work out a path that improves reviewability.

This could potentially close #7 ("agree on test framework" part).

### CODE REVIEW

**Comment by duesee** [comment]
I went through some open PRs and think this could be reviewed -- although it could be more pleasant. Is this a direction you would like to go with the code? If so, I can improve the presentation of this PR.

**Comment by jrfaller** [comment]
Hi!

I think it's a really good idea to modularize the code and have some tests! I am therefore totally on board for merging this PR ;-)

What do you think is missing in the PR?

**Comment by duesee** [comment]
> What do you think is missing in the PR?

Oh, sorry for being unclear. I think the changes itself should be okay. I was just wondering if I could improve how I present the changes to you, e.g., if I should split the first commit, try to separate code moves and code changes, etc. so that it is easier to review.

If this is already acceptable, it would be great to merge :-)

**Comment by jrfaller** [comment]
BTW what is the easiest way to run the tests?

**Comment by duesee** [comment]
You need to install [pytest](https://docs.pytest.org/en/7.2.x/) and run `pytest` in the `tests` folder. There is also a `tests/requirements.txt` that contains `pytest`. Thus, `pip3 install -r requirements.txt` (in the `tests` folder) should work. Maybe we should create a short `README.md` as a follow-up?

**Comment by jrfaller** [comment]
Yes it would be a great idea!

**Pull request merged**
